#! /usr/bin/env bash

# 使用awk把路径包含进去
raw_index_files=$(git diff --cached --raw)
index_files=$(echo "${raw_index_files}" | awk 'BEGIN {FS=" "}/(\.c$)|(\.cpp$)|(\.cc$)|(\.cxx$)|(\.h$)|(\.hpp$)/{print $6}')

ret_code=0
str_done='Done processing'

for ele in ${index_files}
do
    res=`cpplint ${ele} 2>&1`
    sub_res=${res:0:15}
    if [ "${sub_res}" != "${str_done}" ]; then
        echo "${res}"
        ret_code=1
        break
    fi
done


# 根据返回值进行提示性输出
if [ ${ret_code} -eq 1 ]; then
    echo ".............. COMMIT FAILURE .............."
else
    echo ".............. COMMIT SUCCESS .............."
fi

exit ${ret_code}
